### ISSUE TITLE
CSS renders correctly in Firefox & Incorrectly in Chrome 

### ISSUE THREAD

**Issue by russmac** [danielstern/range.css#13]
Chrome: Version 54.0.2840.59 (64-bit)
Firefox: 45.4.0 ESR
[http://pasteboard.co/mJFObw9Xm.png](http://pasteboard.co/mJFObw9Xm.png)

I used the generator at http://danielstern.ca/range.css/#/ it doesnt seem to matter what combination or default I use. It seems chrome ignores it.

Interestingly when you zoom in once %110, the chrome sliders turn blue but nothing like the other style.

**Comment by danielstern** [comment]
Hmm, very strange. I'd be happy to look into a Pull Request for this

**Comment by russmac** [comment]
Yes, its not cross browser compatible. I'm a back end engineer sorry I cant help with a PR.
