### ISSUE TITLE
Background Color issues when using within flexbox display on mobile devices

### ISSUE THREAD

**Issue by rabbitwerks** [danielstern/range.css#20]
Ive come across a display issue when using custom css range inputs within divs using flexbox as display.

It cause the background color of the slider to show through, like adding padding to the top or bottom of the range input would do. When trying to correct with background-color: transparent, it fixed the background color showing, but the slider BG color becomes transparent as well. 

This behavior only seems to happen on mobile device rendering. Can be achieved in the dev tools using the mobile device view as well.
![4ff70caba5caf1053a292f27a7535990](https://user-images.githubusercontent.com/36274332/44971481-4e73f480-af1b-11e8-894c-a0ead2be90db.png)

**Comment by danielstern** [comment]
Dang @Sharpie360 this is a tricky one, alright, I'd be happy to look at a pull request

**Comment by Sharpie360** [comment]
I can do some research and see what i can find.

**Comment by Sharpie360** [comment]
I found a solution that just requires to wrap the input in a div with the display: block. 
Flexbox on the input directly affects the style dimensions resulting in the undesired look.
Therefore enclosing the input inside a standard div that acts as the flex item, achieves the desired result.

I can add a PR with this info for troubleshooting to the docs if possible, i don't think it warrants some sort of built in css class / html markup.
