### ISSUE TITLE
[Feature Request] Group selectors?

### ISSUE THREAD

**Issue by claweyenuk** [danielstern/range.css#22]
Is it possible to use group selectors to reduce the amount of CSS output?

```
input[type=range]::-webkit-slider-runnable-track,
input[type=range]::-moz-range-track {
```

There are other opportunities as well for setting some parameters that are used by multiple browser specific selectors, then putting differences under browser specific selectors, for example `input[type=range]::-ms-fill-lower` and `input[type=range]::-ms-fill-upper`

**Comment by danielstern** [comment]
There currently are no plans for this as the potential gains (slightly reduced file size) are outweighed by the costs (dev time and potential, unexpected incompatibilities.)

Still happy to look at PR for this if its forthcoming though
