### ISSUE TITLE
View in IE

### ISSUE THREAD

**Issue by LeusMaximus** [danielstern/range.css#4]
In the IE looks like this http://prntscr.com/5c2wfb

**Comment by eosterberg** [comment]
There seems to be a bug in the `input[type=range]::-ms-thumb` declaration; `height` is declared twice:
`input[type=range]::-ms-thumb {
  box-shadow: 1px 1px 1px #111111, 0px 0px 1px #1e1e1e;
  border: 1px solid white;
  height: 30px;
  width: 30px;
  border-radius: 8px;
  background: #555bc8;
  cursor: pointer;
  height: 10px; // HERE
}`

Remove it and it works fine in IE10 and Edge.

**Comment by danielstern** [comment]
I'd b happy to check out a PR for this

**Comment by remisture** [comment]
There is a workaround where you use a transparent border on the ::ms-track: http://jsfiddle.net/Lzqb9c46/1/

**Comment by Sora2455** [comment]
This is a very old thread, but just pointing out that there are CSS selectors that are only used in IE: https://stackoverflow.com/a/20541859/7077589

**Comment by danielstern** [comment]
Still maintained. Happy to look at a PR for this.
________________________________
