### ISSUE TITLE
Different behaviours on different Android versions

### ISSUE THREAD

**Issue by smargarita** [danielstern/range.css#7]
Hi.
I developped a app fror Android using Intel XDK.
I installed this app on Samsung S3 Neo (Android 4.4.2) and range.css works fine.
Installed this same app on Samsung S3 (Android 4.3) the format of the Thumb works fine but the Track doesn't change when changing css. It remains always white and thin (1 or 2 points).

Any suggestion or help is welcome.

Range.css is a nice application, thanks.

**Comment by CKH4** [comment]
My thought is that the android 4.3 web engine only supports thumbs, not sliders. I'm pretty sure that there's nothing that the dev could do to help you.
