### ISSUE TITLE
vertical orientation not supported

### ISSUE THREAD

**Issue by bobboau** [danielstern/range.css#9]
If one wanted vertical orientation range inputs there does not seem to be a way to make that happen. Not sure if there is anything that can be done about this because I think it's a problem with how the control is specified/implemented. But I figured I'd point it out in case you can come up with something.

**Comment by Sora2455** [comment]
[MDN suggests](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/range#Change_the_orientation) using `transform: rotate(-90deg);` to achieve this effect.
